/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TipRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "PLATFORM_BPS" | "dropToken" | "platformTreasury" | "tip"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Tip"): EventFragment;

  encodeFunctionData(
    functionFragment: "PLATFORM_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dropToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tip",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "PLATFORM_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dropToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tip", data: BytesLike): Result;
}

export namespace TipEvent {
  export type InputTuple = [
    from: AddressLike,
    dj: AddressLike,
    amount: BigNumberish,
    platformFee: BigNumberish,
    streamId: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    dj: string,
    amount: bigint,
    platformFee: bigint,
    streamId: string
  ];
  export interface OutputObject {
    from: string;
    dj: string;
    amount: bigint;
    platformFee: bigint;
    streamId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TipRouter extends BaseContract {
  connect(runner?: ContractRunner | null): TipRouter;
  waitForDeployment(): Promise<this>;

  interface: TipRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PLATFORM_BPS: TypedContractMethod<[], [bigint], "view">;

  dropToken: TypedContractMethod<[], [string], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  tip: TypedContractMethod<
    [dj: AddressLike, amount: BigNumberish, streamId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PLATFORM_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dropToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tip"
  ): TypedContractMethod<
    [dj: AddressLike, amount: BigNumberish, streamId: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Tip"
  ): TypedContractEvent<
    TipEvent.InputTuple,
    TipEvent.OutputTuple,
    TipEvent.OutputObject
  >;

  filters: {
    "Tip(address,address,uint256,uint256,bytes32)": TypedContractEvent<
      TipEvent.InputTuple,
      TipEvent.OutputTuple,
      TipEvent.OutputObject
    >;
    Tip: TypedContractEvent<
      TipEvent.InputTuple,
      TipEvent.OutputTuple,
      TipEvent.OutputObject
    >;
  };
}
